services:
  load-balancer:
    image: nginx:alpine
    container_name: load-balancer
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9999:9999"
    networks:
      - backend
    depends_on:
      - backend-1
      - backend-2
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "8MB"
  backend-1: &backend
    image: joaovitortst/resilient-payment-router:latest
    hostname: backend-1
    networks:
      - backend
      - payment-processor
    ports:
      - "8081:8080"
    environment:
      - PAYMENT_PROCESSOR_URL_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_URL_FALLBACK=http://payment-processor-fallback:8080
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xmx48m -Xms16m -XX:MaxRAM=72m
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "80MB"

  backend-2:
    <<: *backend
    hostname: backend-2
    ports:
      - "8082:8080"
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true